version: "3.8"
services:
  pacman:
    build: ./frontend
    hostname: pacman
    ports:
     - "1234:80"
  highscore-service:
    build: ./backend/HighscoreService
    hostname: highscore-service
    ports: 
      - "8080:8080"
    depends_on: 
      - mongodb-service
    environment:
      - SPRING_DATA_MONGODB_.HOST=mongodb-service
  mongodb-service:
    image: mongo:latest
    container_name: mongodb-service
    hostname: mongodb-service
    ports: 
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
